name: ESLint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: eslint:github-action
